apiVersion: v1
kind: ConfigMap
metadata:
  name: database-secret
  labels:
    app: database
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:16
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: database-secret
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: database
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: database
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  name: database-clusterip
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - port: 5432
      nodePort: 30002