apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-api-config
  labels:
    app: webhook-api
data:
  RESTAURANT_API_URL: 'http://restaurant-api-clusterip.default.svc.cluster.local:8080'
  WEBHOOK_PORT: "9002"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-api
  template:
    metadata:
      labels:
        app: webhook-api
    spec:
      containers:
        - name: webhook-api
          image: negreirosdev/webhook-server:latest
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: webhook-api-config
          ports:
            - containerPort: 9002
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webhook-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webhook-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-api-clusterip
spec:
  type: NodePort
  selector:
    app: webhook-api
  ports:
    - protocol: TCP
      port: 9002
      nodePort: 30004